"""Added 'limit' column

Revision ID: 25e18ab80e6f
Revises: 
Create Date: 2023-09-08 18:07:53.351200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '25e18ab80e6f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('id', table_name='members')
    op.create_unique_constraint(None, 'members', ['username'])
    op.alter_column('promocodes', 'individual_activations_count',
               existing_type=mysql.TINYINT(unsigned=True),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'limit',
               existing_type=mysql.SMALLINT(),
               nullable=False,
               existing_server_default=sa.text("'20'"))
    op.drop_index('id', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('id', 'users', ['id'], unique=False)
    op.alter_column('users', 'limit',
               existing_type=mysql.SMALLINT(),
               nullable=True,
               existing_server_default=sa.text("'20'"))
    op.alter_column('promocodes', 'individual_activations_count',
               existing_type=mysql.TINYINT(unsigned=True),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.drop_constraint(None, 'members', type_='unique')
    op.create_index('id', 'members', ['id'], unique=False)
    # ### end Alembic commands ###
