"""refactoring

Revision ID: 28221c63311c
Revises: 
Create Date: 2023-12-19 21:00:07.656620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '28221c63311c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('promocodes',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('promocode', sa.String(length=255), nullable=False),
    sa.Column('activations_count', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('individual_activations_count', mysql.TINYINT(unsigned=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('promocode')
    )
    op.create_table('user_dialogues',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('fullname', sa.Text(), nullable=False),
    sa.Column('referrer', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_subscriber', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_command_time', sa.Text(), nullable=True),
    sa.Column('command_count', mysql.SMALLINT(unsigned=True), nullable=False),
    sa.Column('chat_type', sa.String(length=255), nullable=False),
    sa.Column('limit', mysql.SMALLINT(unsigned=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('user_dialogues')
    op.drop_table('promocodes')
    op.drop_table('members')
    # ### end Alembic commands ###
