"""empty message

Revision ID: 9f9c378ad213
Revises: 
Create Date: 2023-09-10 01:42:51.150463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9f9c378ad213'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model')
    op.create_unique_constraint(None, 'members', ['username'])
    op.alter_column('promocodes', 'individual_activations_count',
               existing_type=mysql.TINYINT(unsigned=True),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'limit',
               existing_type=mysql.SMALLINT(),
               nullable=False,
               existing_server_default=sa.text("'20'"))
    op.drop_index('id', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('id', 'users', ['id'], unique=False)
    op.alter_column('users', 'limit',
               existing_type=mysql.SMALLINT(),
               nullable=True,
               existing_server_default=sa.text("'20'"))
    op.alter_column('promocodes', 'individual_activations_count',
               existing_type=mysql.TINYINT(unsigned=True),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.drop_constraint(None, 'members', type_='unique')
    op.create_table('model',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('model_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('default_limit', mysql.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('premium_limit', mysql.SMALLINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
