"""DB

Revision ID: ccd64465f2ad
Revises: 
Create Date: 2023-08-20 00:02:13.006292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ccd64465f2ad'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('id', table_name='users')
    op.drop_index('user_id', table_name='users')
    op.drop_table('users')
    op.drop_index('promocode', table_name='promocodes')
    op.drop_table('promocodes')
    op.drop_index('id', table_name='members')
    op.drop_index('user_id', table_name='members')
    op.drop_table('members')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('username', mysql.TEXT(), nullable=True),
    sa.Column('nickname', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id', 'members', ['user_id'], unique=False)
    op.create_index('id', 'members', ['id'], unique=False)
    op.create_table('promocodes',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('promocode', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('activations_count', mysql.TINYINT(unsigned=True), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('individual_activations_count', mysql.TINYINT(unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('promocode', 'promocodes', ['promocode'], unique=False)
    op.create_table('users',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('fullname', mysql.TEXT(), nullable=True),
    sa.Column('is_blocked', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('is_admin', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('command_count', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('last_command_time', mysql.TEXT(), nullable=True),
    sa.Column('is_subscriber', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('chat_type', mysql.VARCHAR(length=255), server_default=sa.text("'gpt-3.5-turbo'"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id', 'users', ['user_id'], unique=False)
    op.create_index('id', 'users', ['id'], unique=False)
    # ### end Alembic commands ###
